name: Bug Report
description: File a bug report
labels: kind/bug
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - IOS
        - macOS
      default: 0
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: Details about the bug.
    validations:      
      required: true

  - type: textarea
    id: version
    attributes:
      label: App version
      description: Get version in app (Settings -> About).
    validations:
      required: true
      
  - type: textarea
    id: cloudProvider
    attributes:
      label: Cloud provider
      description: Add cloud provider name here, if the bug related to a cloud provider's cluster.
    validations:
      required: false
