name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: kind/bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: Please provide details about the bug.
    validations:      
      required: true

  - type: textarea
    id: version
    attributes:
      label: App version
      description: Please provide App version, Settings -> About.
    validations:
      required: true

  - type: textarea
    id: platform
    attributes:
      label: Platform OS type
      description: Please provide OS type, ios, android, macos, etc.
    validations:
      required: true

  - type: textarea
    id: cloudProvider
    attributes:
      label: Cloud provider
      description: Please provide cloud provider, if the bug is related to a cluster of some cloud provider.
    validations:
      required: false
