name: Feature request
description: Provide details for a feature
labels: kind/enhancement
body:
  - type: markdown
    id: feature
    attributes:
      label: What would you like to be added?
      description: Describe detailed functionality of the feature you request.
    validations:      
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: false
